### ISSUE TITLE
{PATH, MNI_DATAPATH, PERL5LIB, MANPATH,LD_LIBRARY_PATH} when {MINC-TOOLKIT} is not set to default during build.

### ISSUE THREAD

**Issue by Dorky-Lever** [BIC-MNI/minc-toolkit-v2#89]
Hi everyone, 

I had to modify the install path for minc-toolkit-v2 into /usr/local  as /opt/ is shared across our cluster. 

I ran the following build: 
[my_build_sh.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3384550/my_build_sh.txt)

and ran the make and make install after modifying the following config files: 
[minc-toolkit-config_csh.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3384555/minc-toolkit-config_csh.txt)
[minc-toolkit-config-sh.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3384556/minc-toolkit-config-sh.txt)

The output of the build, make and install are given in the following logs: 
[mybuild.log](https://github.com/BIC-MNI/minc-toolkit-v2/files/3384570/mybuild.log)
[myinstall.log](https://github.com/BIC-MNI/minc-toolkit-v2/files/3384571/myinstall.log)
[mymakefin.log](https://github.com/BIC-MNI/minc-toolkit-v2/files/3384572/mymakefin.log)

I compared the {PATH,LD_LIBRARY_PATH,CPATH,ANTSPATH,PYTHONPATH,PERL5LIB,MANPATH and MNI_DATAPATH} to what was set on the MINC-VM (https://github.com/CobraLab/MINC-VM) and realised that our install was missing directories  (e.g. the appropriate /usr/local/* was missing in {PATH,LD_LIBRARY_PATH,PERL5LIB, MANPATH and MNI_DATAPATH}). 
Additionally, the equivalent MNI_DATAPATH folder (opt/minc/share) was missing. 

I manually added the missing paths into my ~/.bash_profile:
[bash_profile.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3384566/bash_profile.txt)

and transferred the MNI_DATAPATH folder to /usr/local/mnishare/ and specified {MNI_DATAPATH} to this location.

Potentially changing the default install path of minc-toolkit-v2 in the config file (i.e. {MINC_TOOLKIT} from /opt/minc/1.9.17 to /usr/local causes the make to miss adding these directories.

**Comment by gdevenyi** [comment]
Did you ``make install``?

All of what you're reporting here works on 10+ systems I have deployed.

**Comment by gdevenyi** [comment]
I'm confused, what is your intended install directory? -DCMAKE_PREFIX_PATH is how you specify where everything will be configured for, including all the paths.

I believe you have somehow misconfused your cmake, as the ``myinstall.log`` clearly states:

> -- Installing: /opt/minc/1.9.17/./bin

This is the root of your issue.

**Comment by gdevenyi** [comment]
Can you share your CMakeCache.txt from inside the build directory?

**Comment by Dorky-Lever** [comment]
Hi Gabriel, 

Our intended install directory is /usr/local/ 

To be sure we configured the right directory, we ran another build as root with minc-toolkit-config.sh and minc-toolkit-config.csh and -DCMAKE_PREFIX_PATH set as /usr/local. (I'm waiting for an administrator to be to available to provide the .log files for this build). 

The paths were still not specified correctly and the test-code gets stuck at the second mincblur pass e.g:

 mincblur -clobber -no_apodize -fwhm 0.28 /home/kyle_arkell/test-data/test-images/img_10jul13.11_C57_dc-deformed-native.mnc MBM_test_processed/img_10jul13.11_C57_dc-deformed-native/tmp/img_10jul13.11_C57_dc-deformed-native_fwhm0.28 -gradient

This is the CMakeCache.txt from the latest build.
[CMakeCache.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3390587/CMakeCache.txt). 

Kind Regards, 
Kyle Drover

**Comment by gdevenyi** [comment]
Can you please show, from initial download to where you get an error, all steps take verbatim with all outputs. 

I don't see any mention of ``source minc-toolkit-config.sh``, for example.

**Comment by Dorky-Lever** [comment]
Hi Gabriel,

It's a bit hard to list all steps as the person who did the install as root is on leave but I'll give it a go.  Please tell me if I have missed something. 

##Installation Steps: ##
> cd /usr/local/src 
> git clone --recursive https://github.com/BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2
> cd minc-toolkit-v2
> mkdir build && cd build

Edited the source minc-toolkit-config.sh and minc-toolkit-config.csh as attached: 
[minc-toolkit-config_csh.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394634/minc-toolkit-config_csh.txt)
[minc-toolkit-config-sh.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394635/minc-toolkit-config-sh.txt)

>  cmake .. \
-DCMAKE_BUILD_TYPE:STRING=Release   \
-DCMAKE_INSTALL_PREFIX:PATH=/usr/local \
-DMT_BUILD_ABC:BOOL=ON   \
-DMT_BUILD_ANTS:BOOL=ON   \
-DMT_BUILD_C3D:BOOL=ON   \
-DMT_BUILD_ELASTIX:BOOL=ON   \
-DMT_BUILD_IM:BOOL=OFF   \
-DMT_BUILD_ITK_TOOLS:BOOL=ON   \
-DMT_BUILD_LITE:BOOL=OFF   \
-DMT_BUILD_SHARED_LIBS:BOOL=ON   \
-DMT_BUILD_VISUAL_TOOLS:BOOL=ON   \
-DMT_USE_OPENMP:BOOL=ON   \
-DUSE_SYSTEM_FFTW3D:BOOL=OFF   \
-DUSE_SYSTEM_FFTW3F:BOOL=OFF   \
-DUSE_SYSTEM_GLUT:BOOL=OFF   \
-DUSE_SYSTEM_GSL:BOOL=OFF   \
-DUSE_SYSTEM_HDF5:BOOL=OFF   \
-DUSE_SYSTEM_ITK:BOOL=OFF   \
-DUSE_SYSTEM_NETCDF:BOOL=OFF   \
-DUSE_SYSTEM_NIFTI:BOOL=OFF   \
-DUSE_SYSTEM_PCRE:BOOL=OFF   \
-DUSE_SYSTEM_ZLIB:BOOL=OFF 

>make 

>make install 

##Install outputs:##
[CMakeCache.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394645/CMakeCache.txt)

/usr/local/minc-toolkit-config.sh and /usr/local/minc-toolkit-config.csh are identical to the configs above. 

##Paths that were missing: ##
{PATH} - /usr/local/pipeline
{LD_LIBRARY_PATH} - /usr/local/bin
{MANPATH} - /usr/local/man
{PERL5LIB}-/usr/local/pipeline and /usr/local/perl
{MNI_DATAPATH} - /opt/minc/share folder was not installed. Manually added this folder and set $MNI_DATAPATH to /usr/local/mnishare

Corrected path environment: 
[all_paths.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394661/all_paths.txt)


##Test-code running: ##
> cd ~
> wget https://github.com/Mouse-Imaging-Centre/pydpiper/archive/master.tar.gz
> tar xzvf master.tar.gz
> wget http://repo.mouseimaging.ca/repo/Pydpiper_test_files/test-data.tar.gz
> tar xzvf test-data.tar.gz

deleted all test images except for img_10* 
> cd test-data/test-images
>rm -r img_07* img_08*  img_09* 
>cd ~

> nano test-data/sample.cfg
# edited config file to: 
[sample_config.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394668/sample_config.txt)

ran the code locally on a sub-node 
> ssh compute-5-2

> mkdir outputs_node

[launch_test_node_sh.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394697/launch_test_node_sh.txt)
> ./launch_test_node.sh


##Outputs from test-code (still running but gets randomly stuck)##
> cd outputs_node/MBM-pipeline

> less pipeline.log
[pipeline.log](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394703/pipeline.log)


> check_pipeline_status.py /home/kyle_arkell/outputs_node/MBM-pipeline/MBM_test_uri
[check_pipeline_status.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394672/check_pipeline_status.txt)

>top 
[top.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394685/top.txt)

##Dependencies configs##
minc2-simple:
> cd /usr/local/src/minc2-simple/build && less CMakeCache.txt
[minc2-simple-CMakeCache.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394711/minc2-simple-CMakeCache.txt)

minc-stuffs: 
> cd /usr/local/src/minc-stuffs/build && less config.log
[config.log](https://github.com/BIC-MNI/minc-toolkit-v2/files/3394727/config.log)

Kind Regards and Thank you for the help

Kyle Drover

**Comment by Dorky-Lever** [comment]
Hi Gabriel, 
I individually ran the three stages that the pipeline was stuck at (ANTS, mincresample and xfminvert in check_pipeline_status.txt) 
ie. 
> ssh compute-5-2

> ANTS 3 --number-of-affine-iterations 0 -m 'CC[MBM_test_processed/img_10jul13.15_C57_dc/resampled/img_10jul13.15_C57_dc_N_I_lsq6_avg_lsq12-resampled.mnc,MBM_test_nlin/MBM_test-nlin-2.mnc,1.0,3]' -m 'CC[MBM_test_processed/img_10jul13.15_C57_dc/tmp/img_10jul13.15_C57_dc_N_I_lsq6_avg_lsq12-resampled_fwhm0.056_dxyz.mnc,MBM_test_nlin/MBM_test-nlin-2/tmp/MBM_test-nlin-2_fwhm0.056_dxyz.mnc,1.0,3]' -t 'SyN[0.1]' -r 'Gauss[2,1]' -i 100x100x100x100 -o MBM_test_processed/img_10jul13.15_C57_dc/transforms/img_10jul13.15_C57_dc_N_I_lsq6_avg_lsq12-resampled_ANTS_to_MBM_test-nlin-2.xfm -x MBM_test_init_model/basket_mouse_brain_mask/resampled/img_10jul13.15_C57_dc_N_I_lsq6_avg_lsq12-resampled_mask.mnc| tee ANTS.log

and all the stages succeeded and produced no errors. 
For example, the ANTS 3 stage took about 2 hours to run but there was no obvious errors: 
[ANTS.log](https://github.com/BIC-MNI/minc-toolkit-v2/files/3395564/ANTS.log).

**Comment by gdevenyi** [comment]
Okay, with full details I can see a few things

> git clone --recursive git@github.com:BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2
This is going to get you master branch, which is not a supported release. Should be:
```
> git clone --recursive --branch release-1.9.17 git@github.com:BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2
```

> Edited the src minc-toolkit-config.sh and minc-toolkit-config.csh as attached:
You're not supposed to be editing those files, those files are automatically modified/copied during "make install"

I still don't see any mention of ``source minc-toolkit-config.sh``.

You cannot just install into a PATH, minc-toolkit requires extra variables defined, which is why you continue to have issues.

Minimal example:
```
> cd ~
>  git clone --recursive --branch release-1.9.17 git@github.com:BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2
> mkdir minc-toolkit-build minc-toolkit-install
> cd minc-toolkit-build
> cmake .. 
-DCMAKE_BUILD_TYPE:STRING=Release 
-DCMAKE_INSTALL_PREFIX:PATH=~/minc-toolkit-install
-DMT_BUILD_ABC:BOOL=ON 
-DMT_BUILD_ANTS:BOOL=ON 
-DMT_BUILD_C3D:BOOL=ON 
-DMT_BUILD_ELASTIX:BOOL=ON 
-DMT_BUILD_IM:BOOL=OFF 
-DMT_BUILD_ITK_TOOLS:BOOL=ON 
-DMT_BUILD_LITE:BOOL=OFF 
-DMT_BUILD_SHARED_LIBS:BOOL=ON 
-DMT_BUILD_VISUAL_TOOLS:BOOL=ON 
-DMT_USE_OPENMP:BOOL=ON 
-DUSE_SYSTEM_FFTW3D:BOOL=OFF 
-DUSE_SYSTEM_FFTW3F:BOOL=OFF 
-DUSE_SYSTEM_GLUT:BOOL=OFF 
-DUSE_SYSTEM_GSL:BOOL=OFF 
-DUSE_SYSTEM_HDF5:BOOL=OFF 
-DUSE_SYSTEM_ITK:BOOL=OFF 
-DUSE_SYSTEM_NETCDF:BOOL=OFF 
-DUSE_SYSTEM_NIFTI:BOOL=OFF 
-DUSE_SYSTEM_PCRE:BOOL=OFF 
-DUSE_SYSTEM_ZLIB:BOOL=OFF
> make && make install
> source ~/minc-toolkit-install/minc-toolkit-config.sh
#I now have a correctly setup and functioning minc-toolkit install, I need to run the source command anytime I want this to happen in a new terminal. A good thing to do here is to add such a line to ~/.bashrc
```

**Comment by Dorky-Lever** [comment]
Hi Gabriel,

I think we fixed the issue by running: 

> ssh compute-5-2
> source /usr/local/src/minc-toolkit-v2/build/minc-toolkit-config.sh
> ./launch_test_node.sh

 
Both MBM.py and MAGeT.py ran successfully but the test-code was halted as RMINC has not yet been installed (I'm currently installing it now).  


Could we please update README.md for minc-toolkit-v2 to include: 

> git clone --recursive --branch release-1.9.17 git@github.com:BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2

and appending source ~/install_path/minc-toolkit-config.sh  to the ./bashrc profile when they need to change the default install path. 



(My apologies, we have the latest version ; the admin who did the install must have run: 
> git clone --recursive --branch release-1.9.17 git@github.com:BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2 
as the first line of minc-tookit-config.sh  within the build directory is: 
> # minc-toolkit configuration parameters for 1.9.17-20190313 )

**Comment by gdevenyi** [comment]
So, to be clear, you weren't sourcing the configuration file, so none of the minc-specific environment variables were defined in your shell, correct?

**Comment by Dorky-Lever** [comment]
Yes,  that is correct. 

I was unaware that you had to source the configuration file. 

Kind Regards,
Kyle Drover

**Comment by Dorky-Lever** [comment]
Hi Gabriel,

I'm launching the test-code in full (i.e. wget the test-data directory, editing sample.cfg to a local run and then launching ./launch.sh locally on a subnode). 

I'm noticing that later stages are being prioritised during the MBM.py run (i.e. mincresample is running on the CPU instead of mincblur etc) and that is causing come of the earlier stages of the pipeline to be stopped. Relaunching the code generally fixes this issue, but why are later stages being prioritized / earlier stages being stopped?

**Comment by gdevenyi** [comment]
That's all pydpiper questions and not relevant here. I'm not a pydpiper developer just a user. Hopefully they can help. Again, full exact commands and logs are essential. I suggest you close your previous issue and open an new one there.
